// Generated by https://quicktype.io

export class Pokemon {
    count:    number | undefined;
    next:     string | undefined;
    previous: null | undefined;
    results:  Result[] | undefined;
}

export class Result {
    name: string | undefined;
    url:  string | undefined;
}
